name: Release Dev

on:
  push:
    branches:
      - 'dev'

jobs:
  tag-dev:
    environment: aws
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle release
        run: ./gradlew release -Prelease.customUsername=${{ secrets.SECRETTOKEN }}