name: Release Master

on:
  push:
    branches:
      - 'master'

jobs:
  tag-dev:
    environment: aws
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle release
        run: ./gradlew release -Prelease.customUsername=${{ secrets.SECRETTOKEN }} -Prelease.versionIncrementer=incrementMinor

      - name: Merge master -> dev
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: master
          target_branch: dev
          github_token: ${{ github.token }}
